spring:
    datasource:
        url: jdbc:mysql://localhost:3306/library?useUnicode=true
        username: donening
        password: 2001zhangyue
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        properties:
            hibername: 
                format-sql: true

server:
    port: 8081